OBJECTS = [
    {"id":"remote","name":"റിമോട്ട്","category":"ഇലക്ട്രോണിക്സ്","color":"കറുപ്പ്","use":"ടിവി മാറ്റാൻ എടുക്കുന്നത്","illustration":"remote","slots":["table-left","shelf-right","chair-seat"],"size":"small"},
    {"id":"phone","name":"ഫോൺ","category":"ഇലക്ട്രോണിക്സ്","color":"നീല","use":"വിളിക്കാൻ ഉപയോഗിക്കുന്നത്","illustration":"phone","slots":["table-center","shelf-left","chair-seat"],"size":"small"},
    {"id":"charger","name":"ചാർജർ","category":"ഇലക്ട്രോണിക്സ്","color":"വെള്ള","use":"ഫോൺ ചാർജ് ചെയ്യുന്നത്","illustration":"charger","slots":["table-right","shelf-left","floor-right"],"size":"small"},
    {"id":"headphones","name":"ഹെഡ്ഫോൺ","category":"ഇലക്ട്രോണിക്സ്","color":"ചുവപ്പ്","use":"കേൾക്കാൻ ഇടുന്ന സാധനം","illustration":"headphones","slots":["chair-back","table-left","shelf-right"],"size":"medium"},
    {"id":"book","name":"പുസ്തകം","category":"പഠനം","color":"പച്ച","use":"വായിക്കാൻ എടുക്കുന്നത്","illustration":"book","slots":["table-left","shelf-center","chair-seat"],"size":"medium"},
    {"id":"pen","name":"പേന","category":"പഠനം","color":"നീല","use":"എഴുതാൻ ഉപയോഗിക്കുന്നത്","illustration":"pen","slots":["table-right","table-center","shelf-left"],"size":"small"},
    {"id":"pencil","name":"പെൻസിൽ","category":"പഠനം","color":"മഞ്ഞ","use":"വരയ്ക്കാൻ ഉപയോഗിക്കുന്നത്","illustration":"pencil","slots":["table-right","shelf-left","floor-left"],"size":"small"},
    {"id":"notebook","name":"നോട്ട്ബുക്ക്","category":"പഠനം","color":"മഞ്ഞ","use":"കുറിപ്പെഴുതാനുള്ളത്","illustration":"notebook","slots":["table-center","shelf-center","chair-seat"],"size":"medium"},
    {"id":"newspaper","name":"പത്രം","category":"പഠനം","color":"വെള്ള","use":"വാർത്ത വായിക്കാൻ എടുക്കുന്നത്","illustration":"newspaper","slots":["table-left","chair-seat","floor-left"],"size":"large"},
    {"id":"bottle","name":"കുപ്പി","category":"അടുക്കള","color":"പച്ച","use":"വെള്ളം കുടിക്കാൻ ഉള്ളത്","illustration":"bottle","slots":["table-right","shelf-right","floor-right"],"size":"medium"},
    {"id":"glass","name":"ഗ്ലാസ്","category":"അടുക്കള","color":"നീല","use":"വെള്ളം കുടിക്കുന്നത്","illustration":"glass","slots":["table-center","table-right","floor-left"],"size":"small"},
    {"id":"cup","name":"കപ്പ്","category":"അടുക്കള","color":"ചുവപ്പ്","use":"ചായ കുടിക്കാൻ എടുക്കുന്നത്","illustration":"cup","slots":["table-left","table-center","shelf-left"],"size":"small"},
    {"id":"plate","name":"പ്ലേറ്റ്","category":"അടുക്കള","color":"വെള്ള","use":"ഭക്ഷണം വയ്ക്കുന്നത്","illustration":"plate","slots":["table-center","table-left","floor-right"],"size":"medium"},
    {"id":"spoon","name":"സ്പൂൺ","category":"അടുക്കള","color":"വെള്ളി","use":"ഭക്ഷണം കഴിക്കാൻ ഉപയോഗിക്കുന്നത്","illustration":"spoon","slots":["table-right","table-center","shelf-left"],"size":"small"},
    {"id":"lid","name":"അടപ്പ്","category":"അടുക്കള","color":"നീല","use":"പാത്രം മൂടാനുള്ളത്","illustration":"lid","slots":["table-left","floor-right","shelf-right"],"size":"small"},
    {"id":"container","name":"ഡബ്ബ","category":"അടുക്കള","color":"ഓറഞ്ച്","use":"സാധനം സൂക്ഷിക്കാൻ ഉള്ളത്","illustration":"container","slots":["table-center","shelf-center","floor-right"],"size":"medium"},
    {"id":"towel","name":"തോർത്ത്","category":"വസ്ത്രം","color":"പിങ്ക്","use":"മുഖം തുടയ്ക്കാൻ എടുക്കുന്നത്","illustration":"towel","slots":["chair-back","shelf-right","floor-left"],"size":"large"},
    {"id":"shirt","name":"ഷർട്ട്","category":"വസ്ത്രം","color":"നീല","use":"ധരിക്കുന്ന വസ്ത്രം","illustration":"shirt","slots":["chair-back","floor-left","shelf-left"],"size":"large"},
    {"id":"folded-cloth","name":"മടക്കിയ തുണി","category":"വസ്ത്രം","color":"മഞ്ഞ","use":"വൃത്തിയാക്കാൻ ഉപയോഗിക്കുന്നത്","illustration":"folded-cloth","slots":["chair-seat","shelf-center","table-left"],"size":"medium"},
    {"id":"handkerchief","name":"റുമാൽ","category":"വസ്ത്രം","color":"വെള്ള","use":"മുഖം തുടയ്ക്കാനുള്ള ചെറിയ തുണി","illustration":"handkerchief","slots":["table-right","chair-seat","shelf-left"],"size":"small"},
    {"id":"sock","name":"സോക്സ്","category":"വസ്ത്രം","color":"പച്ച","use":"കാലിൽ ഇടുന്നത്","illustration":"sock","slots":["floor-left","chair-seat","floor-right"],"size":"small"},
    {"id":"shopping-bag","name":"ഷോപ്പിംഗ് ബാഗ്","category":"ബാഗ്","color":"ഓറഞ്ച്","use":"സാധനം കൊണ്ടുവരാനുള്ള ബാഗ്","illustration":"shopping-bag","slots":["floor-right","chair-back","floor-left"],"size":"large"},
    {"id":"cloth-bag","name":"തുണി സഞ്ചി","category":"ബാഗ്","color":"പച്ച","use":"സാധനം കൊണ്ടുപോകാനുള്ള സഞ്ചി","illustration":"cloth-bag","slots":["floor-left","chair-back","shelf-right"],"size":"large"},
    {"id":"purse","name":"പേഴ്സ്","category":"ബാഗ്","color":"ചുവപ്പ്","use":"പണം വയ്ക്കുന്നത്","illustration":"purse","slots":["table-left","chair-seat","shelf-left"],"size":"small"},
    {"id":"backpack","name":"ബാക്ക്പാക്ക്","category":"ബാഗ്","color":"നീല","use":"തോളിൽ ഇടുന്ന ബാഗ്","illustration":"backpack","slots":["chair-back","floor-right","shelf-right"],"size":"large"},
    {"id":"keys","name":"താക്കോൽ","category":"വ്യക്തിപരം","color":"വെള്ളി","use":"വാതിൽ തുറക്കാനുള്ളത്","illustration":"keys","slots":["table-right","shelf-left","floor-left"],"size":"small"},
    {"id":"umbrella","name":"കുട","category":"വ്യക്തിപരം","color":"ചുവപ്പ്","use":"മഴയിൽ ഉപയോഗിക്കുന്നത്","illustration":"umbrella","slots":["floor-right","chair-back","shelf-right"],"size":"large"},
    {"id":"spectacles","name":"കണ്ണട","category":"വ്യക്തിപരം","color":"കറുപ്പ്","use":"കാണാൻ സഹായിക്കുന്നത്","illustration":"spectacles","slots":["table-left","shelf-center","chair-seat"],"size":"small"},
    {"id":"comb","name":"ചീപ്പ്","category":"വ്യക്തിപരം","color":"പിങ്ക്","use":"മുടി ചീകാൻ എടുക്കുന്നത്","illustration":"comb","slots":["table-right","shelf-left","chair-seat"],"size":"small"},
    {"id":"watch","name":"വാച്ച്","category":"വ്യക്തിപരം","color":"കറുപ്പ്","use":"സമയം നോക്കാൻ ഉള്ളത്","illustration":"watch","slots":["table-center","shelf-right","chair-seat"],"size":"small"},
    {"id":"torch","name":"ടോർച്ച്","category":"ഉപകരണം","color":"മഞ്ഞ","use":"ഇരുട്ടിൽ വെളിച്ചം കാണിക്കുന്നത്","illustration":"torch","slots":["table-left","shelf-right","floor-right"],"size":"medium"},
    {"id":"scissors","name":"കത്രിക","category":"ഉപകരണം","color":"വെള്ളി","use":"മുറിക്കാൻ ഉപയോഗിക്കുന്നത്","illustration":"scissors","slots":["table-right","shelf-left","floor-left"],"size":"small"},
    {"id":"tape","name":"ടേപ്പ്","category":"ഉപകരണം","color":"മഞ്ഞ","use":"ഒട്ടിക്കാൻ ഉപയോഗിക്കുന്നത്","illustration":"tape","slots":["table-center","shelf-right","floor-left"],"size":"small"},
    {"id":"hair-clip","name":"മുടിക്ക്ലിപ്പ്","category":"വ്യക്തിപരം","color":"പിങ്ക്","use":"മുടി പിടിപ്പിക്കാൻ ഉള്ളത്","illustration":"hair-clip","slots":["table-left","shelf-left","chair-seat"],"size":"small"},
    {"id":"mirror","name":"കണ്ണാടി","category":"വ്യക്തിപരം","color":"വെള്ളി","use":"മുഖം നോക്കാൻ ഉള്ളത്","illustration":"mirror","slots":["shelf-center","table-left","chair-back"],"size":"medium"},
    {"id":"cushion","name":"തലയണ","category":"വീട്","color":"ഓറഞ്ച്","use":"ചാരിയിരിക്കാൻ ഉള്ളത്","illustration":"cushion","slots":["chair-seat","floor-left","chair-back"],"size":"large"},
    {"id":"lunch-box","name":"ലഞ്ച് ബോക്സ്","category":"അടുക്കള","color":"പച്ച","use":"ഭക്ഷണം കൊണ്ടുപോകുന്നത്","illustration":"lunch-box","slots":["table-center","chair-seat","shelf-right"],"size":"medium"},
    {"id":"small-clock","name":"ചെറിയ ക്ലോക്ക്","category":"വീട്","color":"ചുവപ്പ്","use":"സമയം കാണിക്കുന്നത്","illustration":"small-clock","slots":["shelf-center","table-left","chair-back"],"size":"medium"},
    {"id":"slipper","name":"ചെരിപ്പ്","category":"വീട്","color":"നീല","use":"കാലിൽ ഇടുന്നത്","illustration":"slipper","slots":["floor-left","floor-right","chair-seat"],"size":"medium"},
    {"id":"toy","name":"കളിപ്പാട്ടം","category":"വീട്","color":"മഞ്ഞ","use":"കളിക്കാൻ ഉള്ളത്","illustration":"toy","slots":["floor-right","shelf-left","chair-seat"],"size":"medium"},
    {"id":"basket","name":"കൊട്ട","category":"വീട്","color":"തവിട്ട്","use":"സാധനങ്ങൾ വയ്ക്കാനുള്ളത്","illustration":"basket","slots":["floor-far-left","floor-mid-right","shelf-left-top"],"size":"large"},
    {"id":"bowl","name":"പാത്രം","category":"അടുക്കള","color":"മഞ്ഞ","use":"ഭക്ഷണം വയ്ക്കാനുള്ളത്","illustration":"bowl","slots":["table-mid-left","table-mid-right","shelf-center-top"],"size":"medium"},
    {"id":"tray","name":"തട്ട്","category":"അടുക്കള","color":"തവിട്ട്","use":"കപ്പുകൾ കൊണ്ടുപോകാനുള്ളത്","illustration":"tray","slots":["table-left","table-center","floor-far-right"],"size":"large"},
    {"id":"brush","name":"ബ്രഷ്","category":"വീട്","color":"നീല","use":"വൃത്തിയാക്കാൻ ഉപയോഗിക്കുന്നത്","illustration":"brush","slots":["table-mid-right","shelf-left-top","floor-mid-left"],"size":"small"},
    {"id":"vase","name":"പൂപ്പാത്രം","category":"വീട്","color":"പിങ്ക്","use":"പൂക്കൾ വയ്ക്കാനുള്ളത്","illustration":"vase","slots":["shelf-center-top","table-right","window-sill-left"],"size":"medium"},
    {"id":"spatula","name":"സ്പാച്ചുല","category":"അടുക്കള","color":"ചുവപ്പ്","use":"അടുക്കളയിൽ ഇളക്കാനുള്ളത്","illustration":"spatula","slots":["table-mid-left","shelf-right-top","floor-mid-right"],"size":"medium"},
    {"id":"bell","name":"മണി","category":"വീട്","color":"വെള്ളി","use":"വിളിക്കാൻ അടിക്കുന്നത്","illustration":"bell","slots":["table-mid-right","shelf-center","chair-seat-left"],"size":"small"},
    {"id":"ruler","name":"സ്കെയിൽ","category":"പഠനം","color":"മഞ്ഞ","use":"അളക്കാൻ ഉപയോഗിക്കുന്നത്","illustration":"ruler","slots":["table-left","window-sill-right","floor-mid-left"],"size":"medium"},
    {"id":"sandal","name":"സാൻഡൽ","category":"വീട്","color":"തവിട്ട്","use":"കാലിൽ ഇടാനുള്ളത്","illustration":"sandal","slots":["floor-far-left","floor-mid-right","floor-far-right"],"size":"medium"},
    {"id":"coaster","name":"കപ്പ് മാറ്റ്","category":"അടുക്കള","color":"പച്ച","use":"കപ്പിന്റെ അടിയിൽ വയ്ക്കുന്നത്","illustration":"coaster","slots":["table-mid-left","table-center","window-sill-right"],"size":"small"},
]

OBJECT_BY_ID = {item["id"]: item for item in OBJECTS}

WRONG_REACTIONS = ["അതല്ല!", "മറ്റേത്!", "അയ്യോ, അതല്ല!", "ഞാൻ ഇതാണോ പറഞ്ഞത്?", "ഒന്ന് നോക്കി എടുക്ക്!", "ഫോൺ നോക്കാൻ മാത്രം നല്ല സ്പീഡാണല്ലോ!"]
REPEATS = ["ഞാൻ പറഞ്ഞില്ലേ… ആ സാധനം!", "അവിടെ ഇരിക്കുന്നത്!", "ഒന്ന് നോക്കിയാൽ കാണാമല്ലോ!"]
ACCEPT = "ഹാ, അതുതന്നെ! ഇതെടുക്കാനാണോ ഇത്ര പാട്?"
RANKS = [(500, "അമ്മയുടെ അംഗീകാരം ലഭിച്ചു! 🏆"), (300, "നല്ല കുട്ടി 😌"), (100, "കുറച്ചുകൂടി ശ്രദ്ധിക്കൂ 😐"), (0, "അമ്മ തന്നെ വന്നെടുത്തു 💀")]
